### ISSUE TITLE
Paraent task and sub-task template

### ISSUE THREAD

**Issue by bymse** [RoboSter/repo-template#3]
### Problem

Hey!

As we are going to implement the project by `feature`s, then we need a way to link `sub-task`s to `feature`. 
Where `feature` is general issue with some links and general purpose. 
`sub-task` is concrete issue that affects part of the `feature`.

### Solution 

- [x] Add/change template for `feature` issue with fields like:
- Description
- Sub tasks list
- Links
- [x] Add labels for `feature` and `sub-task`.

Optional: add automation for links between `feature` and `sub-task`s

### Alternatives 

Don't do it.

### Additional Info

- [As example](https://github.com/RoboSter/server/issues/6)

**Comment by katunilya** [comment]
I considered `groundwork` as a sub task because

`feature` is aimed to explain why we need to implement something
`groundwork` is made for explaining how we want to make something technically

We can just link `feature` issue with all her `groundwork`s after creating them

Possibly we don't need this change at all

**Comment by bymse** [comment]
And what's about template and automation?

**Comment by katunilya** [comment]
done in 0f84b2f00bb4666051f8bc2577e99f41a0597a4e
